### ISSUE TITLE
The picture on About page messes up when viewing with non-standard resolution or from mobile.

### ISSUE THREAD

**Issue by paulbgtr** [AshM10/ashmoreno-portfolio-project#1]
<img width="300px" align-centre src="https://user-images.githubusercontent.com/102642008/197346463-43d2d7cd-8c71-4225-9972-dd9eff6b46be.png">

### Solution I found:

Setting the width directly in the <img≥ tag.

HTML:

```
<img
  width="560px"
  src="images/ashm.jpg"
  class="img-fluid ashm-photo"
  alt="Ash's photo"
/>
```

CSS:

```
.ashm-photo {
  border-radius: 15px;
}
```

**Comment by AshM10** [comment]
Woohoo, thank you so much! I'll work on this soon ♥️
